name: Node.js CI

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm build
        env:
          CI: true
