name: Node.js CI

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm build
        env:
          CI: true
