name: Update PRs and deploy

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate with GitHub
        with:
          script: |
            git config --global user.email "adamma2048@gmail.com"
            git config --global user.name "adamma1024"
            echo "//github.com:$GITHUB_TOKEN" > ~/.git-credentials
            git config credential.helper 'store --file=~/.git-credentials'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - name: Fetch and Deploy
        with:
          script: |
            npm i pnpm -g
            pnpm i
            pnpm run deploy_after_fetch
