name: Update PRs and deploy

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run deploy_after_fetch
