name: Update PRs and deploy

on:
  push:
    branches:
      - all

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i pnpm -g
      - run: pnpm i
      - run: pnpm run deploy_after_fetch
