name: Update PRs and deploy

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - name: Fetch and Deploy
        run: |
          npm i pnpm -g
          pnpm i
          pnpm run deploy_after_fetch
