name: Update PRs and deploy

on:
  push:
    branches:
      - master
      - releases/*
  pull_request:
    branches:
      - master
      - releases/*

jobs:
  pullRequestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_EMAIL: ${{ secrets.EMAIL }}
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
        run: |
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USERNAME
          git remote set-url origin https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/myPortfolio.git
          npm i pnpm -g
          pnpm i
          pnpm run deploy_after_fetch
